services:
  auctionservice-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5106:8080"
      - "7275:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Host=auctionservice-db;Port=5432;Database=auctionservice_dev;Username=auctionservice;Password=Dev@Password123
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      auctionservice-db:
        condition: service_healthy
    networks:
      - auction-network

  auctionservice-db:
    image: postgres:16-alpine
    container_name: auctionservice-db
    environment:
      POSTGRES_DB: auctionservice_dev
      POSTGRES_USER: auctionservice
      POSTGRES_PASSWORD: Dev@Password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auctionservice -d auctionservice_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auction-network

volumes:
  postgres_data:

networks:
  auction-network:
    driver: bridge